COPY	START	4096
FIRST	STL		RETADR
CLOOP	JSUB	RDREC
		LDA		LENGTH
		COMP	ZERO
		JEQ		ENDFIL
		JSUB	WRREC
		J		CLOOP
ENDFIL	LDA		EOF
		STA		BUFFER
		LDA		THREE
		STA		THREE
		JSUB	WRREC
		LDL		RETADR
		RSUB
EOF		BYTE	C'EOF'
THREE	WORD	3
ZERO	WORD	0
RETADR	RESW	1
LENGTH	RESW	1
BUFFER	RESB	4096
SEMICO	BYTE	X'3B'
NEWLIN	BYTE	X'0A'
.
.		SUBROUTINE TO READ RECORD INTO BUFFER
.
RDREC	LDX		ZERO
		LDA		ZERO
RLOOP	TD		STDIN			. LOOP UNTIL INPUT READY
		JEQ		RLOOP
		RD		STDIN
		COMP	NEWLIN
		JEQ		EXIT
		STCH	BUFFER, X
		TIX		MAXLEN
		JLT		RLOOP
EXIT	STX		LENGTH
		RSUB
STDIN	BYTE	X'00'
MAXLEN	WORD	4096
.
.		SUBROUTINE TO WRITE RECORD FROM  BUFFER
.
WRREC	LDX 	ZERO
WLOOP	TD		STDOUT
		JEQ		WLOOP
		LDCH	BUFFER, X
		WD		STDOUT
		TIX		LENGTH
		JLT		WLOOP
		RSUB
STDOUT	BYTE	X'01'
		END		FIRST
